### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by cursedcoder** [jakubledl/dissect#1]
Is it possible to not split Token and Regex for end-user? For example, define it as "Terminal" and check which Recognizer to choose internally in Dissect.

What do you think about it?

**Comment by jakubledl** [comment]
I've considered this idea, however I believe there are some practical issues to it. How exactly should a string be recognized as a regular expression?

Checking whether it begins and ends with a `/` is not sufficient, since a regex might contain modifier flags
or use different delimiters altogether (`@a@`, `~a~` and `(a)` are all valid PCRE regexes). Furthermore, if I wanted to have, say, an operator `//` for integer division in my language, it would be incorrectly recognized as an empty regex.

Plus, I believe that certain amount of explicitness is useful in a DSL. The call to `regex(...)` warns that recognition of this token will be more complex than matching a simple string and, for example, could be optimized.
